[package]
name = "wtldr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html2text = "0.12.2"
openai_api_rust = "0.1.8"
reqwest = { version = "0.11.24", features = ["blocking"] }
